### ISSUE TITLE
could we fund this to go beyond experimental?

### ISSUE THREAD

**Issue by alexlatif** [imaqtkatt/grape#7]
- virtualization of different hardware driver (CUDA, HIP) where core targeting happens
- native drivers when found losing virtual overhead
- eventual singularity container based environments for HPC workloads

we're a group of AI companies supporting the Rust ecosystem to build full stack AI systems. Would you be interested to connect?

**Comment by imaqtkatt** [comment]
It is "experimental" because the VM is on the cpu side but it is also a project for learning. I don't know if this is something I want for the project and I don't have the knowledge for it
